### ISSUE TITLE
User with limited rights dedicated only for monitoring

### ISSUE THREAD

**Issue by Merhaut** [nextcloud/serverinfo#100]
Hi,
I would like suggest to add user with limited rights (or user group) wich will be dedicated only for monitring. I want use XML with my external service but I am little afraid to use administrator account for it.
Thank you

**Comment by MorrisJobke** [comment]
Best here would be a random token that only allows this endpoint. Similar to what was requested in https://github.com/nextcloud/server/issues/7474

**Comment by doobry-systemli** [comment]
That would be really nice to have and is a requirement for using the serverinfo output for proper monitoring.

In my eyes, using a full-featured Nextcloud user for accessing he serverinfo data from your monitoring software is not an option for security reasons.

**Comment by doobry-systemli** [comment]
Any news on that? Just a friendly nudge as I'd love to see this feature :)

**Comment by oddmean** [comment]
As @MorrisJobke said you could use your existing account,


 "Create new app password" in Settings -> Security, then you just find the token in sessions list and disable filesystem access for it. Here is a [screenshot](https://ibb.co/nwveap).

**Comment by doobry-systemli** [comment]
Mh, I'm not convinced. In order to use the metrics from the XML, I need HTTPS access with the user credentials. According to my tests, `/apps/serverinfo/api/v1/info` is not accessible via HTTPS using app passwords.

Besides, it still seems a bit weird to use admin login credentials for requesting the monitoring metrics even when the permissions for these credentials are stripped down.

**Comment by cguentherTUChemnitz** [comment]
I want to use this mechanism for the docker health checking system. This enables us the possibility of executing the health check command inside the docker container server instance itself running against localhost. So **whitelist localhost connections** would be really nice here.

@MorrisJobke What do you think about this proposal? Maybe you can look on what i want to achieve in https://github.com/nextcloud/docker/issues/676

**Comment by MorrisJobke** [comment]
> @MorrisJobke What do you think about this proposal? Maybe you can look on what i want to achieve in [nextcloud/docker#676](https://github.com/nextcloud/docker/issues/676)

See my comment over there.

**Comment by hypervtechnics** [comment]
So... This is the obligatory question: Any news on this?

**Comment by PVince81** [comment]
Another idea would be if there could be an occ command that outputs the monitoring data as json, this would then remove the need for providing any credentials

**Comment by paulfantom** [comment]
>  Another idea would be if there could be an occ command that outputs the monitoring data as json, this would then remove the need for providing any credentials

That would be cached information with no guarantee that the file didn't go stale. Best practice for prometheus exporter says that exporter should fetch data only when prometheus is sending a request to the said exporter and any form of caching data in-between is a no-go. Additionally what would trigger file creation? Because if `occ` command would be executed by the exporter, then the exporter gets even more privileges than before.

**Comment by colttt** [comment]
> Best practice for prometheus exporter says that exporter should fetch data only when prometheus is sending a request to the said exporter and any form of caching data in-between is a no-go. 

who said it's just for prometheus? the goal is to get the data without to create a user with admin rights.
> Additionally what would trigger file creation? 

Which file creation? He said occ can output it, normally just to stdout. And it would be triggered by the NMS-User when it needed (eg the server ask for it)

> Because if `occ` command would be executed by the exporter, then the exporter gets even more privileges than before.

again it exists a lot of monitoring tools and not just prometheus. Beside that, its not true. At the moment I must create an Adminuser(!) in nextcloud, with the occ thing I just need a normal (Unix)user with rights to run this specific command

**Comment by paulfantom** [comment]
Sorry, I mixed this issue with #139 hence my prometheus assumptions.

>  with the occ thing I just need a normal (Unix)user with rights to run this specific command

This is not viable in containerized environments.

**Comment by PVince81** [comment]
quick and dirty PR: https://github.com/nextcloud/serverinfo/pull/269
makes it work but not very elegant
