### ISSUE TITLE
Oracle Database Information not shown

### ISSUE THREAD

**Issue by DavidB3** [nextcloud/serverinfo#102]
### Steps to reproduce
1. Click on Information in Settings Page
2. Look at Database Information

### Expected behaviour
Version and Database size displayed in the appropriate field.

### Actual behaviour
Fields are empty.

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** Apache 2.4

**Database:** Oracle Database 11g2 (11.2.0)

**PHP version:** 

**Nextcloud version:** 
Nextcloud 13.0.0 alpha Build:2017-08-02T22:01:14+00:00 ea2e629c6ca307704dea0aed106dfcb8c0bcc559

**Where did you install Nextcloud from:**
latest-master.zip

**List of activated apps:**
Enabled:
  - activity: 2.6.0
  - comments: 1.3.0
  - dav: 1.4.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.0
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.0
  - twofactor_backupcodes: 1.2.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

**Nextcloud configuration:**

```
<?php
$CONFIG = array (
  'supportedDatabases' => 
  array (
    0 => 'oci',
  ),
  'trusted_domains' => 
  array (
    0 => '192.168.147.143',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'http://192.168.147.143/nextcloud',
  'instanceid' => '**********************************',
  'passwordsalt' => '***************************************',
  'secret' => '*******************************************',
  'dbtype' => 'oci',
  'version' => '13.0.0.2',
  'dbname' => 'gislap1',
  'dbhost' => '',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbtablespace' => 'NextCloud',
  'dbuser' => 'NextCloud',
  'dbpassword' => '********************',
  'installed' => true,
  'theme' => '',
  'loglevel' => 1,
  'maintenance' => false,
);
```

### Client configuration
**Browser:** Firefox 54.0.1 (32 bit)

**Operating system:** Windows 10 64 Bit

#### Nextcloud log (data/owncloud.log)
```
{"reqId":"P1ycEWB1TNBscoCtst7S","level":3,"time":"2017-08-03T12:18:16+00:00","remoteAddr":"192.168.147.1","user":"admin","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/settings\/admin\/serverinfo","message":"Undefined index: version at \/var\/www\/nextcloud\/apps\/serverinfo\/lib\/DatabaseStatistics.php#76","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"13.0.0.2"}
{"reqId":"P1ycEWB1TNBscoCtst7S","level":3,"time":"2017-08-03T12:18:17+00:00","remoteAddr":"192.168.147.1","user":"admin","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/settings\/admin\/serverinfo","message":"Undefined index: dbsize at \/var\/www\/nextcloud\/apps\/serverinfo\/lib\/DatabaseStatistics.php#148","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"13.0.0.2"}
```

**Comment by kesselb** [comment]
Thanks for your bug report :+1: 

Was fixed by https://github.com/nextcloud/serverinfo/pull/256
