### ISSUE TITLE
Add phpinfo() output

### ISSUE THREAD

**Issue by oparoz** [nextcloud/serverinfo#107]
We have minimal information about the PHP configuration.
It would be good to have a hidden panel which can be expanded to reveal the full configuration.

**Comment by Tarry91** [comment]
I want to second this idea! It would be really useful, especially because the nextcloud integrety check fails if one adds his own phpinfo.php file.

**Comment by KopfKrieg** [comment]
It would also be nice to have phpinfo() available in the official docker container. Otherwise I have to modify the container, which is something I'd like to avoid. Having the output of phpinfo() somewhere in the settings would solve this problem.

**Comment by dreua** [comment]
Any news on this topic or solutions you found in the meantime?

**Comment by kesselb** [comment]
Implemented by https://github.com/nextcloud/serverinfo/pull/469
