### ISSUE TITLE
Error in FreeBSD (Swap)

### ISSUE THREAD

**Issue by tflidd** [nextcloud/serverinfo#108]
On NC13beta1.

Use serverinfo on a FreeBSD system. 

`{"reqId":"QKrCFayFmbKiLz4RuNxG","level":3,"time":"2017-12-10T22:06:44+00:00","remoteAddr":"2001:::","user":"user","app":"PHP","method":"GET","url":"\/index.php\/apps\/serverinfo\/update","message":"Undefined index: swap_total at \/usr\/local\/www\/apache24\/data\/nextcloud\/apps\/serverinfo\/lib\/SystemStatistics.php#62","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"13.0.0.6"}`

https://github.com/nextcloud/serverinfo/pull/105 introduced a separate curve for swap usage which is not read yet from FreeBSD systems.

quick workaround: just send `0` values or `N/A` for swap
real solution: implement swap read-out on FreeBSD

**Comment by MorrisJobke** [comment]
@Noodlesalat mind to have a look at this?
