### ISSUE TITLE
[QUESTION] Adding Code

### ISSUE THREAD

**Issue by c0fe** [nextcloud/serverinfo#116]
So this is the code I have written in order to obtain the disk space and insert the data into variables:

```
$os = php_uname('s');
if ($os == "Linux") {
    $freeSpace = disk_free_space("/");
    $diskSpace = disk_total_space("/");
} else {
    $freeSpace = disk_free_space("C:");
    $diskSpace = disk_total_space("C:");
}
$usedSpace = ($diskSpace - $freeSpace);
```

But I am a bit confused as to how to properly add this into the existing php code and call out the variables. I am not very experienced with the P and T translation setup. Can anyone please advise on how to do this properly?

**Comment by MorrisJobke** [comment]
We don't support windows - sorry.

> I am not very experienced with the P and T translation setup. Can anyone please advise on how to do this properly?

The l10n system that is used for translations is something different and should be unrelated to the disk space itself.

For more details you can find examples in the documentation: https://docs.nextcloud.com/server/13/developer_manual/app/l10n.html

**Comment by c0fe** [comment]
@MorrisJobke ok so the corrected code would be:

$freeSpace = disk_free_space("/");
$diskSpace = disk_total_space("/");
$usedSpace = ($diskSpace - $freeSpace);

so how would I properly inject this code and call upon the variables and yet maintain the translation capabilities in Nextcloud ServerInfo?

**Comment by MorrisJobke** [comment]
The big question is what do you want to accomplish. Because the available space on / doesn’t necessarily tell anything about the available space inside Nextcloud. There is another open ticket for the total available space in Nextcloud as well

**Comment by c0fe** [comment]
No I want to get the total free space on the entire disk not just within Nextcloud directory.

So I want the following:

- Total Space of the disk
- Total Free Space of the disk
- Total Used Space of the disk

**Comment by MorrisJobke** [comment]
> No I want to get the total free space on the entire disk not just within Nextcloud directory.

That's not really helpful for Nextcloud itself, because one does not know if this is the only mount point of if the data directory is on a different partition or on a NFS mount point or on an object storage. So if you this should be integrated then all or nothing. Either all mount points are added or none, because otherwise it's a misleading information. On the other hand I still doubt that this makes sense to be included into Nextcloud because there are dozens of tools out there for monitoring and redoing it inside Nextcloud makes very little sense to me. 

cc @nickvergessen @rullzer

**Comment by c0fe** [comment]
@MorrisJobke yes there are other tools but it shouldn't be assumed that they are used, the information is important so you can now how close your Nextcloud instance is at hard drive capacity in a easier to access format than using SSH or using another program.

**Comment by MorrisJobke** [comment]
> @MorrisJobke yes there are other tools but it shouldn't be assumed that they are used, the information is important so you can now how close your Nextcloud instance is at hard drive capacity in a easier to access format than using SSH or using another program.

Still this is only part of the story. This only works if you have one partition. What if you have multiple partitions and Nextcloud uses something else. Then this information doesn't work for you.

**Comment by c0fe** [comment]
@MorrisJobke If that's the case with multiple partitions then most likely the user would be utilizing a third party monitoring application. My solution was aimed at more simplistic usages.

The most complicated setup I have seen at least was a separation between the OS and any other additional applications that do not make up the "core" of the OS, for example, openssh server.

That being said, I feel that this is still a useful item to have, especially if you just use a simple partition scheme for the hard drive.

**Comment by MorrisJobke** [comment]
@nextcloud/designers @nickvergessen @schiessle @rullzer @blizzz Any opinions on this?

**Comment by blizzz** [comment]
I am with @MorrisJobke here, this is likely to create more confusion then add info. This app is meant to give an overview about your Nextcloud server, but not the underlying system. So, you can argue having some monitoring info in Nextcloud is nice, but then I think it's rather a separate app.

**Comment by jancborchardt** [comment]
Agree with @MorrisJobke and @blizzz
