### ISSUE TITLE
Own user group for accessing the API

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/serverinfo#118]
I don't know if i should post it here or in nextcloud/server.

If I want to monitor the API from an external system, I have to use a user with admin rights. Often these credentials are stored in plain text (see nagios).

Wouldn't it make sense to create a new default group (for example "api"), whose users can use the cloud normally and are also allowed to query the api (via Webinterface & REST). The user is only supposed to monitor the system, he will never add a user or install an app.

Admins should of course continue to query the API.

Or maybe with the option "Limit to groups"
![image](https://user-images.githubusercontent.com/16019165/39764167-4f0d5690-52df-11e8-9880-50d852562f87.png)

**Comment by DanScharon** [comment]
I strongly support this proposal. I don't want my monitoring system to have admin credentials, not even an app password I could revoke.

**Comment by kainhofer** [comment]
I can only second that feature request. While the serverinfo app allows limiting it to groups, accessing it via the API still requires admin privileges (I tried adding a "Monitoring" group, but the user got "404 Unauthorized" unless I also added him to the admin group!), so I have to scatter admin password for all my nextcloud installations in plain text all over my icinga2 installation...

For monitoring, requiring admin privileges is certainly overkill and arguably even a security risk (the monitoring system should never have the rights to do any harm!).

**Comment by Starkstromkonsument** [comment]
I would highly appreciate this enhancement too!

BTW: Is this a Duplicate of #100 ?

**Comment by J0WI** [comment]
Duplicate of #100
