### ISSUE TITLE
API delivers wrong data for num_shares_link_no_password

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/serverinfo#119]
I think the API delivers wrong data for `num_shares_link_no_password`.

The following sharing settings are configured. All links should and are password protected!
![image](https://user-images.githubusercontent.com/16019165/42271844-a50fa5e4-7f84-11e8-8c0e-0b0264679ca0.png)

![image](https://user-images.githubusercontent.com/16019165/42271902-ca007a7c-7f84-11e8-8ad6-2569d7e6de4c.png)

If i query the api the values for `num_shares_link`and `num_shares_link_no_passwords` are identical:

![image](https://user-images.githubusercontent.com/16019165/42272087-55064142-7f85-11e8-90dd-235374d0a2bd.png)

If i share a new file/folder (password protected), both values are increased by 1.

According to our monitoring system, the problem has been occurring since 2018/02, before this the value was always 0.
![image](https://user-images.githubusercontent.com/16019165/42271753-64461e30-7f84-11e8-90bf-3b5b28c28d4a.png)

System Info:
- Nextcloud 13.0.4
- Monitoring 1.3.0
- CentOS 7 / Apache / PHP 7.0

**Comment by Spheron101** [comment]
I can confirm this. Same sharing config in server ("Always ask for Password").  ".num_shares_link" + ".num_shares_link_no_password" shows always the same value.

**Comment by orandev** [comment]
Hello,
Solved here: https://github.com/nextcloud/serverinfo/pull/246
