### ISSUE TITLE
Server version 16 or higher is required.

### ISSUE THREAD

**Issue by orlpower** [nextcloud/serverinfo#140]
Linux Version: Alpine Linux (3.9.0_rc1)
Nextcloud Version: 15.0.2
Serverinfo Version: 1.6.0

After putting serverinfo-master into apps directory. It shows up under deactivated apps at the web interface. As reason for deactivation it claims missing dependencies: Server version 16 or higher is required.

![hint](https://user-images.githubusercontent.com/5130305/51185264-ef65b980-18d6-11e9-895e-d6ec927e3feb.png)

**Comment by patschi** [comment]
The `master` branch is based on the most recent code, which might already have dependencies for some yet unreleased Nextcloud versions - like NC 16. I'd rather recommend using the corresponding stable branch for the NC version you use - like [stable15](https://github.com/nextcloud/serverinfo/tree/stable15) in your case.

But beside that, as far as I remember the `serverinfo` app should be shipped by default with Nextcloud?

**Comment by orlpower** [comment]
Seems that i got a version without this app (apk). Now i've copied the suggested stable15, activation was successful but theres an internal server error... so far i've to dig down this further. Thanks for your response.
