### ISSUE TITLE
A non-numeric value encountered at DefaultOs.php#52

### ISSUE THREAD

**Issue by pixel8383** [nextcloud/serverinfo#172]
When browsing the /serverinfo section of my admin panel, I get on the error log:

`A non-numeric value encountered at /usr/local/www/nextcloud/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#52`

The page itself seems ok, it's displayed as expected anyway.

**Comment by tflidd** [comment]
Can you give more information about your system?
If you have terminal access, could you run this command:
`cat /proc/meminfo | grep MemTotal`

It seems that parsing of this output goes wrong.

**Comment by pixel8383** [comment]
It's a freeBSD machine, so I can use `sysctl hw.realmem`
The answer is:
`hw.realmem: 25769803776`

**Comment by Soygen** [comment]
I'm seeing this same error in my log. I'm also running FreeBSD(FreeNAS system with NextCloud running in a jail). Have you figured out how to resolve this?

**Comment by pvuchetich** [comment]
I also see the same issue using the FreeNAS 11.2-U7 Nextcloud plugin. The technical issue is DefaultOs.php parses a Linux-specific file to extract system information. In FreeNAS (FreeBSD 11.2 OS) jail, the "/proc" directory is empty, so the fix would be to use an OS-specific command.  FreeBSD isn't on the list of supported platforms, so there are two ways to resolve this:

See if there are FreeNAS-specific workarounds (community forum for FreeNAS, with a specific group for the Nextcloud plugin) (I did not find one, so I posted a new message)

https://www.ixsystems.com/community/threads/new-install-of-nextcloud-error-message-with-a-non-numeric-value-encountered-at-defaultos-php-52.83329/

The general forum for the FreeNAS Nextcould plugin:
https://www.ixsystems.com/community/forums/Nextcloud/

Or...
Even though it is not an officially supported OS, would it be worth making a pull request with changes to the server information page to check the OS, and use FreeBSD-specific commands? It might take me a bit to figure this out, as I haven't used Nextcloud or looked at its code before today.

**Comment by pixel8383** [comment]
Another easy fix? This one: check the OS version and if it's not a valid one, just avoid to extract informations.
I know it would be better to build FreeBSD specific queries but if the OS is listed as non supported, this could just fix the issue.

**Comment by VVD** [comment]
@pixel8383, @pvuchetich, @Soygen, plz, check my patch at #203.

**Comment by kesselb** [comment]
Fixed by #210 for Nextcloud 20.
