### ISSUE TITLE
Memory "Current usage" is misleading on older kernels

### ISSUE THREAD

**Issue by lbdroid** [nextcloud/serverinfo#181]
This is related to older bug here: https://github.com/nextcloud/serverinfo/issues/43
Fix for which is here:
https://github.com/nextcloud/serverinfo/commit/5c3bc559aacca2c62d536907771c5a1825266cbe

The issue is that on any server that has any moderate amount of disk usage, the amount of "free" memory will always tend to be close to zero, or at least much closer to zero than what should be reported, due to caching. What the fix does, is it switches to using MemAvailable instead of MemFree where MemAvailable is... available, which is correct, but leaves older kernels out in the cold.

MemAvailable can be calculated for older kernels as the SUM of MemFree + Buffers + Cached.

**Comment by kesselb** [comment]
How old is your kernel? :thinking: That feature seems to be available for a while.

**Comment by kesselb** [comment]
Thanks for your bug report :+1: 

I guess we require a newer kernel then.
