### ISSUE TITLE
CPU name appearing multiple times in CPU column

### ISSUE THREAD

**Issue by HigH-HawK** [nextcloud/serverinfo#182]
### Steps to reproduce
1. Login as admin
2. Got to Settings -> System

### Expected behaviour
The CPU column should only show the CPU name once and it's cores in brackets / parenthesis

Example:

```
CPU: AMD Opteron(tm) Processor 3280 (4 cores)
```

### Actual behaviour
I have a quad core CPU in the server and the CPU name appears 8 times on my page including the listing of my cores. It appears 8 times, since it has SMT/CMT

This is how it looks:

```
CPU: AMD Opteron(tm) Processor 3280 AMD Opteron(tm) Processor 3280 AMD Opteron(tm) Processor 3280 AMD Opteron(tm) Processor 3280 AMD Opteron(tm) Processor 3280 AMD Opteron(tm) Processor 3280 AMD Opteron(tm) Processor 3280 AMD Opteron(tm) Processor 3280 (4 4 4 4 4 4 4 4 cores)
```

### Server configuration

**Operating system**: Debian 9.12 (stretch)

**Web server:** Apache/2.4.25 (Debian)

**Database:** mysql  Ver 15.1 Distrib 10.3.22-MariaDB

**PHP version:** 7.2.28

**Nextcloud version:** 18.0.2

**Where did you install Nextcloud from:** ZIP package at version 15

---

I could fix this by amending line 65 and 66 in `serverinfo/lib/OperatingSystem/DefaultOs.php`

https://github.com/nextcloud/serverinfo/blob/b609cc7897f29666ef37744b10bb26b0f2d903ec/lib/OperatingSystems/DefaultOs.php#L65-L66

**Old:**
```PHP
$cpu   = shell_exec('cat /proc/cpuinfo  | grep -i \'Model name\' | cut -f 2 -d ":" | awk \'{$1=$1}1\'');
$cores = shell_exec('cat /proc/cpuinfo  | grep -i \'cpu cores\' | cut -f 2 -d ":" | awk \'{$1=$1}1\'');
```

**New:**
```PHP
$cpu   = shell_exec('cat /proc/cpuinfo  | grep -i \'Model name\' | cut -f 2 -d ":" | awk \'{$1=$1}1\' | head -1');
$cores = shell_exec('cat /proc/cpuinfo  | grep -i \'cpu cores\' | cut -f 2 -d ":" | awk \'{$1=$1}1\' | head -1');
```

**Comment by HigH-HawK** [comment]
@karlitschek please could you review the above and maybe add it to the next release?

Thanks in advance

**Comment by karlitschek** [comment]
This makes sense. Can you create a pull request. Happy to merge it

**Comment by HigH-HawK** [comment]
Just noticed that there is already pull to revamp the information gathering opened by @kesselb 

Pull: #183 

Had a look at the code change and think the new one is better, since it doesn't use `shell_exec()`

I'm not too familiar with GitHub pull/merge stuff, so I might have missed the information, whether this pull is only meant for NC 19 or if there is also going to be a backport for 16, 17, 18

@kesselb can you confirm whether there are plans to implement the change in 16, 17 and 18 as well?

**Comment by kesselb** [comment]
19 only. Feel free to submit a patch for the current release. First again master and then as backport to stable18 (will be done by a bot).
