### ISSUE TITLE
Extension OPcache

### ISSUE THREAD

**Issue by Gunnar-GO** [nextcloud/serverinfo#197]
As an extension a Informationblock about the PHP opcache would be practical.

an example is given in an discussion entry:

https://help.nextcloud.com/t/http-error-500-when-trying-to-access-nextcloud/33646/3

it generates a detailed informationpage, that could served as a template.

**Comment by Starkstromkonsument** [comment]
Yes, this would make things easier! Same goes for #196 

I currently use a quick and dirty workaround:

1. Create the directory `stats` in the root of your Nextcloud-Installation (This might not survive a server upgrade! It is better to create this directory outside of your NC-root and symlink it into it.) 
2. Setup .htaccess an .htpasswd for `AuthType Basic` to restrict the access to this folder
3. Create the file `stats/opcache_json.php` with the following content:
``` php
<?php
// Script for printing a json-array for parsing by a monitoring solutuion

$status = opcache_get_status(false);

echo json_encode($status, JSON_PRETTY_PRINT);
?>
```
4. Query `https://<URL-TO-YOUR-NEXTCLOUD>/stats/opcache_json.php` with your monitoring server.

BTW: You can do the same for #196 by adding the file `stats/apc_json.php` with the following content:

``` php
<?php
// Script for printing a json-array for parsing with zabbix

$cache = apcu_cache_info(true);
$sma = apcu_sma_info(true);

$result = array ("cache" => $cache, "sma" => $sma);

echo json_encode($result, JSON_PRETTY_PRINT);
?>
```

Maybe this inspires sombody to submit a PR to append this to the "official" serverinfo-array.
