### ISSUE TITLE
Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent

### ISSUE THREAD

**Issue by j-ed** [nextcloud/serverinfo#198]
## Current behavior
If a serverinfo api call is initiated the following message is written to the log file:
```
...,"app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/serverinfo/api/v1/info","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"curl/7.69.0","version":"18.0.3.0"}
```
## Steps to reproduce
1. Use the given url to initiate a serverinfo api query.
2. Check the Nextcloud log file and find the given message.

#### Server Configuration
OS: Linux 4.9.215
Web server: Apache2 2.4.41
Database: MariaDB 10.2.24
PHP version: 7.3.13
Nextcloud version: 18.0.3
**Serverinfo app version: 1.8.0**

#### Client Configuration
Browser: Mozilla Firefox 75.0
Operating system: Windows 10

**Comment by joshtrichards** [comment]
See nextcloud/server#37816 for the latest (and various others, if you're so inclined).

This is an non-event (essentially) and can be safely ignored. 

In any case, it's being triggered by a call in the class `\OCP\Files` (part of NC server itself) not the `serverinfo` app. 

Nothing for us to do here.
