### ISSUE TITLE
Consider replacing while loop in FormatBytes

### ISSUE THREAD

**Issue by J0WI** [nextcloud/serverinfo#207]
https://github.com/nextcloud/serverinfo/blob/efeed3479fd048b403c6a72ebf74241a971a065c/templates/settings-admin.php#L28-L36

This doesn't look very efficient and could be replaced with a logarithmic function. Requires check for `<= 0`.

**Comment by kesselb** [comment]
https://3v4l.org/Jh2PS/perf
https://3v4l.org/PbVrs/perf

**Comment by joshtrichards** [comment]
This seems settled and can be closed. :)
