### ISSUE TITLE
Reverse order of active users

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/serverinfo#21]
<img width="641" alt="web-ui2" src="https://cloud.githubusercontent.com/assets/4638605/17482030/34297d50-5d80-11e6-9639-d8c15342ae83.png">

The x-axis of active users goes from present to past. It should be the other way around as with all time-based graphs.

@Ivansss

**Comment by jancborchardt** [comment]
Alos @Ivansss @schiessle it seems that »last 24 hours« and »last 1 hour« always include the values from the value before. This will _always_ result in a downward trend or a straight line. So from the value of »Last 1 hour« we should subtract the »Last 5 mins« value, and from »Last 24 hours«, both further future values should be subtracted.

**Comment by schiessle** [comment]
@jancborchardt sure, because if you where active in the last 5 minutes, then you where also active in the last hour and in the last 24 hours.

In general, the whole number is a bit tricky because we get this number by looking at the active sessions in the sessions table. But if a user logout the session gets removed, so we will no longer count this user. But most people will probably just close their browser or shut down their sync client.

**Comment by schiessle** [comment]
> The x-axis of active users goes from present to past. It should be the other way around as with all time-based graphs.

Really? All coordinate systems I know start by '0' and not by the highest value. Remember all the coordinate systems you draw in math or physics during school? The values always increases along the axis, not decreases.

**Comment by jancborchardt** [comment]
@schiessle all graphs which have time as a factor go from left to right to show the development over time. It has nothing to do with the cartesian system starting at 0.

To make the graph more useful I suggest we change it as mentioned above. In the future it should be like a proper activity graph over time as a Wordpress blog shows. Sure if you were active 5 minutes ago you were also active the last hour, but it doesn’t really make sense visualization-wise. The data we should really represent is the number of users who was active the last 24 hours, but hour by hour so a nice development graph will be shown. Do we have this data though?

**Comment by schiessle** [comment]
Yes, we could also do it per hour, we have the timestamp of the last activity. But then maybe a block chart would be nicer. Then you could even label the blocks not by hour 1 to hour 24 but by the actual time,e.g. 1pm-2pm, 2pm-3pm,... which might be even more interesting. And then I also agree that it makes sense to change the order to start with the past and go to present

**Comment by jancborchardt** [comment]
Cool! But then we should still use a line chart. Bar chart is for comparisons of different values, line charts are for developments of the same value, which this is.
