### ISSUE TITLE
l10n: Translation and incorrect value

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/serverinfo#232]
### Steps to reproduce
1. Select "Settings".
2. Select "System".

### Expected behaviour
Full translation in the native language. Valid values.

### Actual behaviour

- No translation:

![obraz](https://user-images.githubusercontent.com/47037905/92390438-24152d00-f11b-11ea-8d1c-12636c7dfed5.png)

- Incorrect value:

![obraz](https://user-images.githubusercontent.com/47037905/92390562-68083200-f11b-11ea-855e-14f53b84e0bc.png)

**Nextcloud version:** (see Nextcloud admin page)
19.0.2

**Comment by kesselb** [comment]
Thanks for your feedback 👍

> No translation

I don't think a translation for unknown processor is necessary. It's the fallback if we are unable to read the processor name.

> Incorrect value

-1 is also the fallback. I guess we are not allowed to read /proc/meminfo and/or /proc/cpuinfo.

**Comment by Valdnet** [comment]
> I don't think a translation for unknown processor is necessary. It's the fallback if we are unable to read the processor name.

@kesselb In my opinion, it should be translated. If the application provides us with the mother tongue, all information contained therein should also be translated into the mother tongue. Then it guarantees us full professionalism.

> -1 is also the fallback. I guess we are not allowed to read /proc/meminfo and/or /proc/cpuinfo.

If the value is 0 or -1, the information should be similar to the processor, i.e. unknown.
