### ISSUE TITLE
Settings: System not working

### ISSUE THREAD

**Issue by vanastasis** [nextcloud/serverinfo#250]
Hi,

Settings: system not displaying CPU, RAM etc...

error:

Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: 10.1.1.1
    Request ID: oGZYlBRjDVd8swftuniE

Running; 
OS : TrueNas 12 / FreeBSD 12.2
Jail base : 12.2 FreeBSD
Jail nextcloud : 20
php : 4.7.10
web server : nginx 1.18
database : mysql 5.7.31
Install : fresh via plugins

index.php/settings/integrity/failed  = no errors

Enabled Apps:
  - accessibility: 1.6.0
  - activity: 2.13.1
  - cloud_federation_api: 1.3.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - files: 1.15.0
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - survey_client: 1.8.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - workflowengine: 2.2.0

Tested on 
- Windows 10, Firefox 82, IE 11, Edge
- Linux, Debian 12, Firefox 82

**Comment by kesselb** [comment]
Mind to check the nextcloud logfile for error messages? Otherwise there is not much we can do. Could be https://github.com/nextcloud/serverinfo/pull/240 which is fixed with Nextcloud 20.0.1 (which is not released yet).

**Comment by vanastasis** [comment]
Hi,

Thank you for the email

when i click on system, it creates 3 logs, see below.

{"reqId":"dQlQC6xwoFjfTMeHTRZL","level":3,"time":"2020-10-09T20:37:47+00:00","remoteAddr":"10.1.1.1","user":"ncadmin","app":"PHP","method":"GET","url":"/settings/admin/serverinfo","message":{"Exception":"Error","Message":"Undefined 
offset: 0 at 
/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php#187","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php","line":187,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/Os.php","line":132,"function":"getNetworkInterfaces","class":"OCA\\ServerInfo\\OperatingSystems\\FreeBSD","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/Settings/AdminSettings.php","line":111,"function":"getNetworkInterfaces","class":"OCA\\ServerInfo\\Os","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/CommonSettingsTrait.php","line":141,"function":"getForm","class":"OCA\\ServerInfo\\Settings\\AdminSettings","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/AdminSettingsController.php","line":83,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController
","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/CommonSettingsTrait.php","line":152,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/AdminSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Ro
ute/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 
(X11; Linux x86_64; rv:82.0) Gecko/20100101 
Firefox/82.0","version":"20.0.0.9","id":"5f80ca1c61750"}

{"reqId":"dQlQC6xwoFjfTMeHTRZL","level":3,"time":"2020-10-09T20:37:47+00:00","remoteAddr":"10.1.1.1","user":"ncadmin","app":"PHP","method":"GET","url":"/settings/admin/serverinfo","message":{"Exception":"Error","Message":"Undefined 
offset: 0 at 
/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php#188","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php","line":188,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/Os.php","line":132,"function":"getNetworkInterfaces","class":"OCA\\ServerInfo\\OperatingSystems\\FreeBSD","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/Settings/AdminSettings.php","line":111,"function":"getNetworkInterfaces","class":"OCA\\ServerInfo\\Os","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/CommonSettingsTrait.php","line":141,"function":"getForm","class":"OCA\\ServerInfo\\Settings\\AdminSettings","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/AdminSettingsController.php","line":83,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController
","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/CommonSettingsTrait.php","line":152,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/AdminSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Ro
ute/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 
(X11; Linux x86_64; rv:82.0) Gecko/20100101 
Firefox/82.0","version":"20.0.0.9","id":"5f80ca1c61697"}

{"reqId":"dQlQC6xwoFjfTMeHTRZL","level":3,"time":"2020-10-09T20:37:47+00:00","remoteAddr":"10.1.1.1","user":"ncadmin","app":"index","method":"GET","url":"/settings/admin/serverinfo","message":{"Exception":"Exception","Message":"strpos() 
expects parameter 1 to be string, null 
given","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"strpos() 
expects parameter 1 to be string, null 
given","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php","line":191,"function":"strpos"},{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/Os.php","line":132,"function":"getNetworkInterfaces","class":"OCA\\ServerInfo\\OperatingSystems\\FreeBSD","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/Settings/AdminSettings.php","line":111,"function":"getNetworkInterfaces","class":"OCA\\ServerInfo\\Os","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/CommonSettingsTrait.php","line":141,"function":"getForm","class":"OCA\\ServerInfo\\Settings\\AdminSettings","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/AdminSettingsController.php","line":83,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/CommonSettingsTrait.php","line":152,"fu
nction":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/AdminSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/local/www/nextclo
ud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/local/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php","Line":191},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 
(X11; Linux x86_64; rv:82.0) Gecko/20100101 
Firefox/82.0","version":"20.0.0.9","id":"5f80ca1c615ea"}

logs files withing nextcloud:log

if it helps.

thank you

- Vas

**Comment by Schueni1** [comment]
OS: FreeBSD 12.1-RELEASE-p10
Nextcloud 20.0.0
php 7.4.11
nginx/1.18.0
10.4.14-MariaDB

I think I am facing exactly the same problem.

`{"reqId":"khTe7egwsXsaAPx4NOpF","level":3,"time":"2020-10-11T00:28:15+00:00","remoteAddr":"192.168.42.1","user":"ad","app":"index","method":"GET","url":"/settings/admin/serverinfo","message":{"Exception":"Exception","Message":"strpos() expects parameter 1 to be string, null given","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AdminSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"serverinfo","action":null,"_route":"settings.AdminSettings.index"}]},{"file":"/usr/local/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/admin/serverinfo"]},{"file":"/usr/local/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"strpos() expects parameter 1 to be string, null given","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php","line":191,"function":"strpos","args":[null,"G"]},{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/Os.php","line":132,"function":"getNetworkInterfaces","class":"OCA\\ServerInfo\\OperatingSystems\\FreeBSD","type":"->","args":[]},{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/Settings/AdminSettings.php","line":111,"function":"getNetworkInterfaces","class":"OCA\\ServerInfo\\Os","type":"->","args":[]},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/CommonSettingsTrait.php","line":141,"function":"getForm","class":"OCA\\ServerInfo\\Settings\\AdminSettings","type":"->","args":[]},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/AdminSettingsController.php","line":83,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":[[[{"__class__":"OCA\\ServerInfo\\Settings\\AdminSettings"}]]]},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/CommonSettingsTrait.php","line":152,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["serverinfo"]},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/AdminSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["admin","serverinfo"]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["serverinfo"]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AdminSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"serverinfo","action":null,"_route":"settings.AdminSettings.index"}]},{"file":"/usr/local/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/admin/serverinfo"]},{"file":"/usr/local/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php","Line":191},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"20.0.0.9","id":"5f8251a41b4c8"}`

`{"reqId":"khTe7egwsXsaAPx4NOpF","level":3,"time":"2020-10-11T00:28:15+00:00","remoteAddr":"192.168.42.1","user":"ad","app":"PHP","method":"GET","url":"/settings/admin/serverinfo","message":{"Exception":"Error","Message":"Undefined offset: 0 at /usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php#188","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php","line":188,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"Undefined offset: 0","/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php",188,{"result":[{"interface":"re0","ipv4":"192.168.42.160","ipv6":"","mac":"00:1e:06:45:2f:70","status":"active","speed":"1000 Mbps","duplex":"Duplex: full"},{"interface":"lo0","ipv4":"127.0.0.1","ipv6":"::1 fe80::1","status":"active","speed":"unknown","duplex":""}],"ifconfig":"re0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500\n\toptions=8209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE>\n\tether 00:1e:06:45:2f:70\n\tinet 192.168.42.160 netmask 0xffffff00 broadcast 192.168.42.255\n\tmedia: Ethernet autoselect (1000baseT <full-duplex>)\n\tstatus: active\n\tnd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>\nlo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384\n\toptions=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>\n\tinet6 ::1 prefixlen 128\n\tinet6 fe80::1%lo0 prefixlen 64 scopeid 0x2\n\tinet 127.0.0.1 netmask 0xff000000\n\tgroups: lo\n\tnd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>\npflog0: flags=141<UP,RUNNING,PROMISC> metric 0 mtu 33160\n\tgroups: pflog\nwg0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1420\n\toptions=80000<LINKSTATE>\n\tinet 10.69.69.1 --> 10.69.69.1 netmask 0xffffffff\n\tgroups: tun\n\tnd6 options=101<PERFORMNUD,NO_DAD>\n\tOpened by PID 747\ntun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1500\n\toptions=80000<LINKSTATE>\n\tinet6 fe80::21e:6ff:fe45:2f70%tun1 prefixlen 64 scopeid 0x5\n\tinet 10.8.0.1 --> 10.8.0.2 netmask 0xffffff00\n\tgroups: tun\n\tnd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>\n\tOpened by PID 1295\n","interfaces":[["re0","lo0","pflog0","wg0","tun1"]],"interface":"pflog0","iface":{"interface":"pflog0","ipv4":"","ipv6":"","mac":"","status":null},"intface":"pflog0: flags=141<UP,RUNNING,PROMISC> metric 0 mtu 33160\n\tgroups: pflog\n","ipv4":[[]],"ipv6":[[],[],[],[]],"mac":[[]],"status":[],"speed":[],"duplex":[]}]},{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/Os.php","line":132,"function":"getNetworkInterfaces","class":"OCA\\ServerInfo\\OperatingSystems\\FreeBSD","type":"->","args":[]},{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/Settings/AdminSettings.php","line":111,"function":"getNetworkInterfaces","class":"OCA\\ServerInfo\\Os","type":"->","args":[]},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/CommonSettingsTrait.php","line":141,"function":"getForm","class":"OCA\\ServerInfo\\Settings\\AdminSettings","type":"->","args":[]},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/AdminSettingsController.php","line":83,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":[[[{"__class__":"OCA\\ServerInfo\\Settings\\AdminSettings"}]]]},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/CommonSettingsTrait.php","line":152,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["serverinfo"]},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/AdminSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["admin","serverinfo"]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["serverinfo"]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AdminSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"serverinfo","action":null,"_route":"settings.AdminSettings.index"}]},{"file":"/usr/local/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/admin/serverinfo"]},{"file":"/usr/local/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/local/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"20.0.0.9","id":"5f8251a41b7fe"}`

`{"reqId":"khTe7egwsXsaAPx4NOpF","level":3,"time":"2020-10-11T00:28:15+00:00","remoteAddr":"192.168.42.1","user":"ad","app":"PHP","method":"GET","url":"/settings/admin/serverinfo","message":{"Exception":"Error","Message":"Undefined offset: 0 at /usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php#187","Code":0,"Trace":[{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php","line":187,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"Undefined offset: 0","/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/OperatingSystems/FreeBSD.php",187,{"result":[{"interface":"re0","ipv4":"192.168.42.160","ipv6":"","mac":"00:1e:06:45:2f:70","status":"active","speed":"1000 Mbps","duplex":"Duplex: full"},{"interface":"lo0","ipv4":"127.0.0.1","ipv6":"::1 fe80::1","status":"active","speed":"unknown","duplex":""}],"ifconfig":"re0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500\n\toptions=8209b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,WOL_MAGIC,LINKSTATE>\n\tether 00:1e:06:45:2f:70\n\tinet 192.168.42.160 netmask 0xffffff00 broadcast 192.168.42.255\n\tmedia: Ethernet autoselect (1000baseT <full-duplex>)\n\tstatus: active\n\tnd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>\nlo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384\n\toptions=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>\n\tinet6 ::1 prefixlen 128\n\tinet6 fe80::1%lo0 prefixlen 64 scopeid 0x2\n\tinet 127.0.0.1 netmask 0xff000000\n\tgroups: lo\n\tnd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>\npflog0: flags=141<UP,RUNNING,PROMISC> metric 0 mtu 33160\n\tgroups: pflog\nwg0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1420\n\toptions=80000<LINKSTATE>\n\tinet 10.69.69.1 --> 10.69.69.1 netmask 0xffffffff\n\tgroups: tun\n\tnd6 options=101<PERFORMNUD,NO_DAD>\n\tOpened by PID 747\ntun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1500\n\toptions=80000<LINKSTATE>\n\tinet6 fe80::21e:6ff:fe45:2f70%tun1 prefixlen 64 scopeid 0x5\n\tinet 10.8.0.1 --> 10.8.0.2 netmask 0xffffff00\n\tgroups: tun\n\tnd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>\n\tOpened by PID 1295\n","interfaces":[["re0","lo0","pflog0","wg0","tun1"]],"interface":"pflog0","iface":{"interface":"pflog0","ipv4":"","ipv6":"","mac":""},"intface":"pflog0: flags=141<UP,RUNNING,PROMISC> metric 0 mtu 33160\n\tgroups: pflog\n","ipv4":[[]],"ipv6":[[],[],[],[]],"mac":[[]],"status":[],"speed":[],"duplex":[]}]},{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/Os.php","line":132,"function":"getNetworkInterfaces","class":"OCA\\ServerInfo\\OperatingSystems\\FreeBSD","type":"->","args":[]},{"file":"/usr/local/www/nextcloud/apps-pkg/serverinfo/lib/Settings/AdminSettings.php","line":111,"function":"getNetworkInterfaces","class":"OCA\\ServerInfo\\Os","type":"->","args":[]},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/CommonSettingsTrait.php","line":141,"function":"getForm","class":"OCA\\ServerInfo\\Settings\\AdminSettings","type":"->","args":[]},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/AdminSettingsController.php","line":83,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":[[[{"__class__":"OCA\\ServerInfo\\Settings\\AdminSettings"}]]]},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/CommonSettingsTrait.php","line":152,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["serverinfo"]},{"file":"/usr/local/www/nextcloud/apps-pkg/settings/lib/Controller/AdminSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["admin","serverinfo"]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->","args":["serverinfo"]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/usr/local/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\AdminSettingsController"},"index"]},{"file":"/usr/local/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\AdminSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"serverinfo","action":null,"_route":"settings.AdminSettings.index"}]},{"file":"/usr/local/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/admin/serverinfo"]},{"file":"/usr/local/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/local/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"20.0.0.9","id":"5f8251a41bb33"}`

**Comment by kesselb** [comment]
Fix #251
