### ISSUE TITLE
i18n fix (german)

### ISSUE THREAD

**Issue by fwolfst** [nextcloud/serverinfo#265]
### Steps to reproduce
1. Install serverinfo `1.10.0`
2. Change language to german
3. visit app page

### The fix
Unfortunately transifex won't let me in (I guess it has to do with privacy and ad blocking, in which case I am sorry for the inconvenience, will not disable that for fun).

https://github.com/nextcloud/serverinfo/blob/d9cc64aa9970dc411c318ca4309a382df7ffd0a4/l10n/de.js#L41
and
https://github.com/nextcloud/serverinfo/blob/d9cc64aa9970dc411c318ca4309a382df7ffd0a4/l10n/de.json#L39

(locale `de`, key `You will get a notification once one of your disks is nearly full.`). In both cases `s/eine Deiner/eines Deiner/` (an `s` is missing).
Translation is corect for the formal German locale (`de_DE`).

**Comment by kesselb** [comment]
cc @rakekniven

**Comment by rakekniven** [comment]
Fixed it right away.
Thanks @fwolfst for reporting!
