### ISSUE TITLE
Travis CI changes

### ISSUE THREAD

**Issue by J0WI** [nextcloud/serverinfo#275]
Travis CI changed their infrastructure and policies for open source repos:
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

It seems that they started to limit the concurrent builds for open source projects recently: https://www.traviscistatus.com/

Tests will stop working completely at some point:

> We are announcing that travis-ci.org will be officially closed down completely no later than December 31st, 2020

https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by J0WI** [comment]
:ping_pong: @nextcloud/server-triage

**Comment by skjnldsv** [comment]
It needs to be moved to github actions
See https://github.com/nextcloud/app-tutorial/tree/master/.github/workflows

**Comment by J0WI** [comment]
Someone with admin privileges is required to enable and configure GitHub apps.

**Comment by skjnldsv** [comment]
Just creating those files is enough.
We don't need github apps there as far as I know :thinking:

**Comment by kesselb** [comment]
We are using GitHub actions nowadays :tada:
