### ISSUE TITLE
Use Light Icons When Using Dark Theme

### ISSUE THREAD

**Issue by ghost** [nextcloud/serverinfo#296]
**Is your feature request related to a problem? Please describe.**
The icons are black by default. Using Dark theme will change most of the icons to white ones, but it doesn't apply on the icons in ServerInfo.

**Describe the solution you'd like**
Apply light icons on Dark theme. It requires CSS abilities which I am currently unable to implement.

### Server configuration

**Nextcloud version:** 21.0.1

**Comment by joshtrichards** [comment]
Fixed by #396
