### ISSUE TITLE
We need a nice icon for the server monitoring app

### ISSUE THREAD

**Issue by schiessle** [nextcloud/serverinfo#3]
Would be good to have a nice icon for the server monitoring app in the apps listing

cc @nextcloud/designers

**Comment by mar1u5** [comment]
What do you think about somehting like this:
http://fontawesome.io/icon/pie-chart/

**Comment by enoch85** [comment]
Other suggestions:

https://www.iconfinder.com/icons/638239/business_graph_monitor_report_icon#size=128
https://www.iconfinder.com/icons/1031365/beat_beats_heartbeat_monitor_screen_icon#size=128
https://www.iconfinder.com/icons/399143/graph_health_monitor_screen_tv_icon#size=128

**Comment by enoch85** [comment]
I can donate the cost btw. $1, take it from my Paypal account :D

**Comment by MorrisJobke** [comment]
I think we will not buy an icon, but will do a simple one ourselves ... cc @jancborchardt

**Comment by MorrisJobke** [comment]
I think @Bugsbane also did some icons in the past

**Comment by schiessle** [comment]
Decided to move it to the admin page, so no icon for the apps menu needed. But would probably still be nice to have a icon for the apps listing

**Comment by Bugsbane** [comment]
I'd rather make a new icon myself than buy one personally.

**Comment by Bugsbane** [comment]
Actually, I had a bit of time, so I ran something up while I was waiting, based on the idea of a heartbeat, or monitoring the wellbeing of your install:

app icon:
![server-monitor-app](https://cloud.githubusercontent.com/assets/401733/17469800/b497a308-5d04-11e6-9abb-c264eafa7615.png)

...and in a mocked up screenshot (I replaced the generic cog icon for the "Collaborative Tags" app, with the new potential Server Monitor app icon.
![server-monirot-app-screenshot-mockup](https://cloud.githubusercontent.com/assets/401733/17469820/db122076-5d04-11e6-8442-b1ca010598ea.png)


Let me know what you think, and if I'm on the right track.

**Comment by schiessle** [comment]
@Bugsbane looks really nice! :+1: Do you want to create a pull request to add the icon? Thanks!

**Comment by Bugsbane** [comment]
Done. Sorry, I accidentally committed straight to master, instead of forking/branching first. Anyway, take a look and let me know if you need anything (like the color) changed.

**Comment by LukasReschke** [comment]
> Done. Sorry, I accidentally committed straight to master, instead of forking/branching first. 

I protected the branches now so that this won't be possible anymore in the future.

**Comment by Bugsbane** [comment]
For future reference @LukasReschke , what's the protocol for committing? Branch, commit and PR? Fork, commit and PR? (In which case what happens when you're working on multiple things and you want to commit the changes for one?) Fork, branch your fork and then PR?

**Comment by LukasReschke** [comment]
Branch, commit and PR <- this. :-)

**Comment by MorrisJobke** [comment]
backported to stable10: stable10 5b6dd3c

**Comment by jancborchardt** [comment]
@Bugsbane hehe, awesome icon work again! :)

**Comment by Bugsbane** [comment]
Thanks! I wish I could say I planned this consciously, but I just noticed the icon has a large "N" hidden in it (as in "N" for Nextcloud 😉 )

**Comment by jancborchardt** [comment]
@Bugsbane :DD
