### ISSUE TITLE
Show systems network bandwidth on system page 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/serverinfo#305]
Hello it would be nice to be able to view the network bandwidth under the system tab like you can see system load and memory.

**Comment by andyxheli** [comment]
@wonderfulShrineMaidenOfParadise Do you know anyway to help out with this ?

**Comment by wonderfulShrineMaidenOfParadise** [comment]
Not sure what you mean. Is it network speed? If so, it's already visible in network section. Otherwise you may need to find out how to get the values from commands or `/sys/class/net/<interface>/*`.
