### ISSUE TITLE
add a filesize overview Widget to nextcloud/dashboard

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/serverinfo#315]
Please add a dashboard plugin to get a [Windirstat](https://windirstat.net/) or [jdiskreport](http://www.jgoodies.com/freeware/jdiskreport/) like overview.

It would be nice to modifier this statistic to show most transferred data on the same directory based overview instead.

For reference: https://github.com/nextcloud/dashboard/issues/39#issuecomment-552865317

**Comment by joshtrichards** [comment]
Hi @Mannshoch - Thanks for your idea. Closing in favor of #226 so that expressions of interest and discussion can be centralized under one issue.
