### ISSUE TITLE
No space character

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/serverinfo#324]
Text strings should be separated by a space after the colon character:

![obraz](https://user-images.githubusercontent.com/47037905/124563777-a3a98080-de40-11eb-85f9-c01f07b5df1d.png)

**Nextcloud version:** (see Nextcloud admin page)
22.0.0 RC2

**Comment by tflidd** [comment]
It's a table:https://github.com/nextcloud/serverinfo/blob/9ae9dde028a684e53a1b37c9ba8e964ffe42a97f/templates/settings-admin.php#L63-L64

So you'd need to fix the css class setting to increase the spacing
