### ISSUE TITLE
Nextcloud Monitoring API „url in JSON“

### ISSUE THREAD

**Issue by Micha222288** [nextcloud/serverinfo#330]
Hello,

is there the possibility to change following strings in common format:

<filelocking.enabled>
<memcache.distributed>
<memcache.local>
<memcache.locking>

A common format would mean to change the "." with "_" like compared to all the other strings. This string is giving JSON Error in Monitoring Solution.

The issue is that the software interprets the "." as two strings. 

EDIT: Is there any description about the calculated values of API url or the multiplier I need to set. There are a few values whatever which multiplier I set, they seem to me without sense. For example APCU-Cache Start time this is not seconds?

Thx for taking care about my question.

Regards
M.

**Comment by joshtrichards** [comment]
> The issue is that the software interprets the "." as two strings.

This sounds like an issue with the monitoring solution's JSON parser. :-)

The issue with renaming these fields is that it breaks things for other people. Sometimes - when a change has been unavoidable - adding copies with different names or structures has been considered from what I've seen in past Issues and PRs (but the prior ones are also left in place alongside so...).

> Is there any description about the calculated values of API url or the multiplier I need to set. There are a few values whatever which multiplier I set, they seem to me without sense. For example APCU-Cache Start time this is not seconds?

Not that I'm aware of. Many values are documented in their respective source (most aren't NC specific). For example, the APCU cache values all come from `apcu_cache_info()`:

https://www.php.net/manual/en/function.apcu-cache-info.php

Sometimes the source describes them well and other times... Not so much. 

That particular one you asked about looks like an epoch time to my eye, but I don't see it documented even at the source.

**Comment by joshtrichards** [comment]
@staeglis wrote: 

> After the update to Nextcloud we can't gather the database size because it's a string now.

I think your report got lost since the Issue you posted this comment on is unrelated.

It does indeed look to be a string (unlike most of the other numeric values). I'm not sure why that is offhand (nor when or if the behavior changed). I haven't run across anyone else impacted by it.

If you're still impacted by this, please submit your own bug report (Issue).
