### ISSUE TITLE
Not displayed name (Version:) for value (only version number without any word before it displayed) for PHP

### ISSUE THREAD

**Issue by p-bo** [nextcloud/serverinfo#340]
### Steps to reproduce
1. Go to Settings -> Administration -> System
2. Look to PHP section
3. Observe only number without any clue what it is expressing

### Expected behaviour
Displayed:
Version: x.x.x

### Actual behaviour
Displayed:
x.x.x

### Server configuration

**Nextcloud version:** 22.2.3

**Where did you install Nextcloud from:**Nexcloud vm

###Additional info:
- the same behavior in Firefox and Chromium
- independent from language set (as opposed to #338)

**Comment by p-bo** [comment]
Would it be possible to fix it the same way as other things in https://github.com/nextcloud/serverinfo/pull/333 please?

**Comment by Valdnet** [comment]
This has been fixed but not added to the new Nextcloud version.
