### ISSUE TITLE
Not displayed name (Type/Version/Size:) for value (only db name / version string / size of database without any word before it displayed) for database

### ISSUE THREAD

**Issue by p-bo** [nextcloud/serverinfo#341]
### Steps to reproduce
1. Go to Settings -> Administration -> System
2. Look to Database section
3. Observe only strings/numbers without any clue what it is expressing

### Expected behaviour
Displayed:
Type: pogsql
Version: PostgreSQL 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
Size: 50.1 MB

### Actual behaviour
Displayed:
pogsql
PostgreSQL 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
50.1 MB

### Server configuration

**Nextcloud version:** 22.2.3

**Where did you install Nextcloud from:**Nexcloud vm

###Additional info:
- the same behavior in Firefox and Chromium
- independent from language set (as opposed to #338)

**Comment by p-bo** [comment]
Would it be possible to fix it the same way as other things in https://github.com/nextcloud/serverinfo/pull/333 please?

**Comment by Valdnet** [comment]
The changes were introduced on Nov 30, 2021 and are still not implemented in the latest version 23.0.1 on Jan 27, 2022. As if the introduced changes were systematically updated in the main Nextcloud release, there would be fewer user reports with the same problem.

@nextcloud-gmbh Please update these changes regularly before the main Nextcloud release. This is the only way to achieve success and professionalism.
