### ISSUE TITLE
External monitoring tool - string "Copied!" shown in English regardless of localization exists

### ISSUE THREAD

**Issue by p-bo** [nextcloud/serverinfo#343]
### Steps to reproduce
1. Set language to something different than English (tested on German and Czech, because they are fully translated on Transifex for long time)
2. Go to Settings -> System -> External monitoring tool and click to copy button near box with end point url
3. See unlocalized Copied! instead of localized string (button label localization is working properly)

### Expected behaviour
Display localized string

### Actual behaviour
Displayed Copied! instead

### Server configuration

**Nextcloud version:** 22.2.3

**Where did you install Nextcloud from:** Nextcloud VM

**Comment by joshtrichards** [comment]
Indeed.

Looks like [this line](https://github.com/nextcloud/serverinfo/blob/bf8ecf6d5f606173f1cb7e219e55933b1c4daeb3/js/script.js#L228) just needs a `t()` applied in the front end:

```

                        OC.Notification.show('Copied!', { type: 'success' })
```

Probably just:

```

                        OC.Notification.show(t('serverinfo', 'Copied!'), { type: 'success' })
```

I'm on mobile at the moment so unable to recompile the front end to commit. Someone else feel free to submit the PR and take full credit. 😅
