### ISSUE TITLE
Bad memory capacity report 

### ISSUE THREAD

**Issue by adosix** [nextcloud/serverinfo#348]
### Steps to reproduce
1. install nextcloud server version 21.0.7 / dsmr thing after update to nextcloud version 22.2.3
2. have ubuntu server installed on SSD (500GB in my case) 
3. mount HDD (8TB in my case)  to user's data folder like (user/files/mountedHDD/)

It's no biggie for now bcs nextcloud is reporting that i have 1.8TB data and nextcloud is reporting that i have 1.8TB filled from 2TB but don t know how it's gonna behave when i reach 2TB and more. For now is everything without problem just that bar and report is irritating
Nextcloud tracker (in settings/personal info)
![image](https://user-images.githubusercontent.com/44939175/147102629-bcf642c0-7143-4f37-aa01-78e0f2ce5e3f.png)

also nextcloud tracker (in settings/system

![image](https://user-images.githubusercontent.com/44939175/147102965-5cb827f3-8b89-4011-a7c9-c04848e7f5d8.png)

**Comment by tflidd** [comment]
@szaimen the output of the serverinfo doesn't look that bad. 4.75 TB + 1.8 TB = 6.55 TB (+ other stuff) <= 6.86 TB
The problem is the remaining storage for the user, is that in the serverinfo app as well?

**Comment by adosix** [comment]
yes that is the problem bcs i have set max limit for the admin user unlimited. More interesting is that when I change unlimited to 5 TB. it s showing limit 2.2TB, With unlimited it s 2 TB. If any of people working on it would like to call and find where is mistake, I will be happy to assist and share screen through discord.

**Comment by tflidd** [comment]
You have a 32bit or 64bit OS?

**Comment by adosix** [comment]
64bit, Ubuntu Linux 20.04.3, and most up to date stable release of nextcloud

**Comment by adosix** [comment]
in user settings, set to unlimited
![mem1](https://user-images.githubusercontent.com/44939175/150533708-95312a0d-ffc0-4826-9785-e87b54190676.jpg)
![mem4](https://user-images.githubusercontent.com/44939175/150533739-e9c91c4e-2def-4c6a-a44c-1e356bb86607.jpg)
:

**Comment by adosix** [comment]
in user settings, set manulally to 6 TB
![mem2](https://user-images.githubusercontent.com/44939175/150533803-1367adf2-c7f6-47a6-9e5a-70df2dfe6d9e.jpg)
![mem3](https://user-images.githubusercontent.com/44939175/150533829-107eb49f-436b-4bb3-938f-a7db8195bfe8.jpg)
:

**Comment by adosix** [comment]
Like... what is going on :D :D :D

**Comment by kesselb** [comment]
Thanks for your bug report :+1: 

I don't think we support mounting an external disk directly inside the users files directory. You may use the files_external app for it. The logic to calculate the free disk space / used quota is part of Nextcloud server and not the serverinfo app.
