### ISSUE TITLE
[Bug]: mobile view in settings > system broken

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/serverinfo#361]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The boxes on the page settings > system is not correct on mobile devices

![EE84F4BB-A4B5-4398-BA41-230A2B901074](https://user-images.githubusercontent.com/1473674/160274785-6335666c-a26c-4ba4-9894-d69488c9d227.jpeg)

### Steps to reproduce

1. open settings > system with an iPhone
2. the boxes are not correct formated 

### Expected behavior

The boxes uses the full width and not 50% of the page

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Default with LDAP, Deck and Talk activated
```

**Comment by szaimen** [comment]
Possible css fix:

```
@media only screen and (max-width: 700px) {
    .col-4, .col-6 {
        flex-basis: 50%;
    	max-width: 50%;
    	min-width: 50%;
        
    }
}

@media only screen and (max-width: 500px) {
    .col-4, .col-6 {
        flex-basis: 100%;
    	max-width: 100%;
    	min-width: 100%;
    }
}

.chart-container canvas {
    max-height:400px;
}
```

**Comment by Dennis1993** [comment]
Thank you, I've created a pull request! 👍
