### ISSUE TITLE
Active users graph is drawn partially outside of its window

### ISSUE THREAD

**Issue by Guillaume99** [nextcloud/serverinfo#37]
Steps to reproduce

  1)  create 2 users and connect
  2) go to Admin/server info
  3)  Active users graph is drawn partially outside of its window (see picture below)

![capture d ecran 2016-08-21 a 12 10 43](https://cloud.githubusercontent.com/assets/20171421/17838612/bf0cbf8a-67d1-11e6-8ecd-d7512c7bca35.png)

**Comment by nickvergessen** [comment]
See #38

**Comment by nickvergessen** [comment]
@Ivansss Can you have a look at this? Also #38 suggests to not use this graph but more a bar thing or whatever

**Comment by Ivansss** [comment]
@jancborchardt suggested to keep using a line chart at #21.
We should make a decision about which type of chart we use.

**Comment by nickvergessen** [comment]
Line chart yes, but more like "connected dots" instead of "draw a curvy S between the values"

**Comment by jancborchardt** [comment]
@Ivansss I think a spline is fine here to make the graph look nice. But having the highest value as the maximum could be better. How about using a rounded value above the highest value as maximum?

Like if 8 is the highest value, we use 10 as maximum. If it’s 56, we use 60 as maximum. Etc.
