### ISSUE TITLE
[Bug]: mobile view of settings > system out of boxes

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/serverinfo#385]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If I open the Settings page as an Admin and go to System tab, the boxes in the screenshot are not breaks in a new line.
I think it would be better to set every box to 100% without floating (only on desktop)

![04953F43-B469-4758-88C2-3C963FCED94C](https://user-images.githubusercontent.com/1473674/171942304-0ff65534-0cd7-485e-a2b4-e280fe32810f.jpeg)
![F34A7306-4E7A-4F22-83D1-EEE7E4CEE015](https://user-images.githubusercontent.com/1473674/171942311-9b804a2f-ba24-45ae-affd-005d28723f69.jpeg)

### Steps to reproduce

1. go to settings > system
2. see wrong aligned boxes

### Expected behavior

Every box should be in a single line

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Not useful
```

**Comment by szaimen** [comment]
Possible css fix:

```
@media only screen and (max-width: 700px) {
    .col-4, .col-6 {
        flex-basis: 50%;
    	max-width: 50%;
    	min-width: 50%;
        
    }
}

@media only screen and (max-width: 500px) {
    .col-4, .col-6 {
        flex-basis: 100%;
    	max-width: 100%;
    	min-width: 100%;
    }
}

.chart-container canvas {
    max-height:400px;
}
```

**Comment by Dennis1993** [comment]
Thank you, I've created a pull request! 👍

**Comment by joshtrichards** [comment]
Possibly related: #320
