### ISSUE TITLE
Adminstrative Script for bug reporting and documentation - II

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/serverinfo#4]
Hi, perhaps the proposed and (WIP) script for bug reporting and documentation 
https://github.com/LukasReschke/issuereporter/tree/initial-import
could be linked ?? or a menu item ?? to the serverinfo app ???

regards, hitam4450

**Comment by nickvergessen** [comment]
https://help.nextcloud.com/t/issue-template-app/2571
