### ISSUE TITLE
Should swap and memory really be the same graph?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/serverinfo#41]
See https://help.nextcloud.com/t/incorrect-total-ram-capacity/2662 for discussion
@schiessle

**Comment by ferdiga** [comment]
IMO it can be on the same graph but the graph should show memory (bottom) and swap (top) separated by a line or in different colors.
As we all know a production server should use swap only exceptionally.

**Comment by patschi** [comment]
Implemented in PR #105
