### ISSUE TITLE
[BITV]: Replace custom tooltips with native one for system settings page

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/serverinfo#418]
## Problem

To show a tooltip on a several components we currently use v-tooltip. v-tooltip is not accessible and we want to migrate to native tooltips (title attribute) instead. 

Besides this it is important to fix cut tooltip and place tooltip information next to the chart because this will be read by screen reader. 

![Screenshot from 2022-12-28 15-14-19](https://user-images.githubusercontent.com/6078378/209825552-630292f0-680c-4247-9358-e928410f8ae9.png)

Further point is about chart legend for "Load" and "Memory". @jancborchardt, @PVince81 should it be added?

Other discussion question is: do we need "Active users" and "Shares" charts? They seems not to be useful. @jancborchardt, @PVince81 what do you think about it? 

An overview can be found in https://github.com/nextcloud/nextcloud-vue/issues/2503.

## Solution

Show tooltip's info in other visible way.

### Steps to reproduce
1. Open ettings/admin/serverinfo
2. Look through different charts and tooltips which belongs to each chart

### Expected behaviour

Charts should not have any important / relevant information inside of tooltip. 

### Actual behaviour
Tooltips are not accessible

### Server configuration
not relevant

**Operating system**:
not relevant

**Web server:**
not relevant

**Database:**
not relevant

**PHP version:**
not relevant

**Nextcloud version:** (see Nextcloud admin page)
not relevant

**Where did you install Nextcloud from:**
not relevant

**List of activated apps:**
not relevant

**Nextcloud configuration:**
not relevant

### Client configuration

**Browser:**
not relevant

**Operating system:**
not relevant

### Logs
not relevant

#### Browser log
not relevant

**Comment by JuliaKirschenheuter** [comment]
Answer from @jancborchardt: 

> Other discussion question is: do we need "Active users" and "Shares" charts? They seems not to be useful. 

Yeah, Shares can definitely be replaced by a simple list. Active users only needs a chart if the time is linear, that is e.g. over last 7 days with 1 data point per day for example.

> Add a title prop to several components that will render as title attribute on the HTML element.

Sounds good. And considering basically all the graphs (except the changing CPU load graphs) have the data as text next to it it’s fine as well.

Answer from @AndyScherzinger: 

"Active users" and "Shares" charts have to be replaced with plain (list) text information

**Comment by AndyScherzinger** [comment]
Woohoo 🎉 A11Y improvements on serverinfo also improve the page in general from a human processing info perspective 👍
