### ISSUE TITLE
[BITV]: Replace custom tooltips with native one for system settings page

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/serverinfo#419]
## Problem

To show a tooltip on a several components we currently use v-tooltip. v-tooltip is not accessible and we want to migrate to native tooltips (title attribute) instead. 

Besides this it is important to fix cut tooltip and place tooltip information next to the chart because this will be read by screen reader. 

![Screenshot from 2022-12-28 15-14-19](https://user-images.githubusercontent.com/6078378/209825552-630292f0-680c-4247-9358-e928410f8ae9.png)

Further point is about chart legend for "Load" and "Memory". @jancborchardt, @PVince81 should it be added?

Other discussion question is: do we need "Active users" and "Shares" charts? They seems not to be useful. @jancborchardt, @PVince81 what do you think about it? 

An overview can be found in https://github.com/nextcloud/nextcloud-vue/issues/2503.

## Solution

Add a `title` prop to several components that will render as `title` attribute on the HTML element.

**Comment by kesselb** [comment]
Hi @JuliaKirschenheuter,

Moved the issue for you to serverinfo repository.

**Comment by JuliaKirschenheuter** [comment]
duplicate of https://github.com/nextcloud/serverinfo/issues/418
