### ISSUE TITLE
debian jessie MemFree instead of MemAvailable

### ISSUE THREAD

**Issue by inos-github** [nextcloud/serverinfo#43]
on my debian jessie, /proc/meminfo shows MemFree instead of MemAvailable, so I had to edit  serverinfo/lib/SystemStatistics.php line 85:
`'mem_free' => (int)$data['MemAvailable'] + (int)$data['SwapFree'],`
to
`'mem_free' => (int)$data['MemFree'] + (int)$data['SwapFree'],`

**Comment by hitam4450** [comment]
Hi,
I am on DEBIAN Jessie (8.4) as well:

Error message:

P	Undefined index: MemAvailable at /var/www/servers/nextcloud-beta/apps/serverinfo/lib/SystemStatistics.php#85

regards, hitam4450

**Comment by schiessle** [comment]
My server also runs on Debian Jessie and I have both "MemFree" and MemAvailable".

**Comment by longsleep** [comment]
Older Kernels will not have MemAvailable, was implemented in 2014 - see https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/proc/meminfo.c?id=34e431b0ae398fc54ea69ff85ec700722c9da773

**Comment by magicsunday** [comment]
My servers runs Ubuntu 14.04.5 LTS

`awk -F" " '{ print $1 $2 }' /proc/meminfo` returns

```
MemTotal:4194304
MemFree:2985428
Cached:1104392
Buffers:0
Active:643340
Inactive:532228
Active(anon):202620
Inactive(anon):271032
Active(file):440720
Inactive(file):261196
Unevictable:0
Mlocked:0
SwapTotal:3145728
SwapFree:3145728
Dirty:16
Writeback:0
AnonPages:473652
Shmem:402476
Slab:33308
SReclaimable:15592
SUnreclaim:17716

```

**Comment by DamienGong** [comment]
MemAvailable is a feature introduced since kernel version 3.16 (?)
