### ISSUE TITLE
Add disk space to output?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/serverinfo#46]
I think we should display the disk space as well

**Comment by hitam4450** [comment]
Well, it has to defined what kind of disc space you are talking about!

The disc space where NC is located (installed) or the disc space where the data is stored? That is not always the same disc space! I reassigned the data folder onto a separate disc form the installation of NC!

regards, hitam4450

**Comment by nickvergessen** [comment]
Same here, of course data dir is what is of interest ;)

**Comment by schiessle** [comment]
I remember that I did a quick test when I started writing the app. The problem I faced was to get the available disc space for /data (remember, it also has to work with external primary storage). Do you have a idea how the get this information with the files view or node api?

**Comment by nickvergessen** [comment]
Well honestly, better to have a value working for everything except external storage, then one that is usless to everyone? ;)

**Comment by ET-Bent** [comment]
To add up to this, please allow an option to show total used storage and storage used by user.

**Comment by GitHubUser4234** [comment]
> To add up to this, please allow an option to show total used storage and storage used by user. (for example in a splitted bar graph or pi-chart)

Absolutely agree to have an option to see the storage used by users, whereas a bar graph would be the preferable way of presentation.

**Comment by brantje** [comment]
Would be nice to see various disk spaces.
Eg:
- From the location where nextcloud is installed.
- As above, used disk space by users.

**Comment by TheMrApostel** [comment]
I agree.
It's not abvious which users storage is used up by checking the log file.
The log file just gives back a 507 Insufficient Storage.

**Comment by brantje** [comment]
Anyway i could add an bounty to fix this issue?

**Comment by Schmuuu** [comment]
There is an update coming for the "User Settings" administrators page. The users used space will be graphically shown in the quota column. So you will see a bar indicating a rough percentage of used space and when mouseover there will be exact values.

I think when this feature will be out (probably with 12.1) there is no need for a user based disc usage in the serverinfo area.
However I would still like to see the overall disc usage.

**Comment by TheMrApostel** [comment]
@Schmuuu 
That would be great! I think you mean 12.0.1? This is going to be released today.
I will upgrade my version to that at the end of the week then.

**Comment by Schmuuu** [comment]
@TheMrApostel 
Yeah I meant 12.0.1, sorry :)
I upgraded my test server to 12.0.1 RC5 yesterday and wanted to review the feature I described. While I couldn't see the feature implemented I searched the Pull Request again and noticed, that it is actually NC 13 that should ship it. Sorry for the misleading.

But maybe it works to change the files accordingly and make it work in 12.0.1 already. Here is the pull request with some screenshots:
https://github.com/nextcloud/server/pull/5342

**Comment by brantje** [comment]
They made a backport to 12.0.1.

> However I would still like to see the overall disc usage.
This would be nice, maybe we can use the output of `df -h`?

**Comment by c0fe** [comment]
Any updates on this?

**Comment by c0fe** [comment]
@nickvergessen

**Comment by nickvergessen** [comment]
Well anyone can pick up the task and add the value to the UI ;)

**Comment by c0fe** [comment]
@nickvergessen is there any design guidelines that must be followed?

**Comment by nickvergessen** [comment]
well it should fit into the existing code/ui

**Comment by JamesBream** [comment]
@nickvergessen This should be pretty easy given that `freespace` already appears in the external monitoring API, right?

I'd be up for taking a crack at this in a few weeks time if no-one else gets to it before then.

**Comment by patschi** [comment]
The `<freespace>` value is now also being displayed in the `Storage` section on the serverinfo page, as done in PR #127.
