### ISSUE TITLE
How to protect monitoring API from guest access?

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/serverinfo#460]
Please, describe, how can I protect or limit access to the data monitoring through the API? Thanks!

**Comment by joshtrichards** [comment]
It already is protected. Are you seeing differently?

**Comment by ostasevych** [comment]
So, anyone

> It already is protected. Are you seeing differently?

Yes, it is. There's a possibility to do it via `token occ config:app:set serverinfo token --value yourtoken`
However, cannot understand in which way?

**Comment by kesselb** [comment]
`ocs/v2.php/apps/serverinfo/api/v1/info` is private by default. 
Users with admin permissions can use the app and api.
