### ISSUE TITLE
Add network throughput?

### ISSUE THREAD

**Issue by Alphakilo** [nextcloud/serverinfo#47]
It'd be nice to see how much traffic is running through the server at a given time.
Even better if there were graphs per NIC.

**Comment by BornToBeRoot** [comment]
@nickvergessen  This would be a great feature!

Maybe also how much a single user consumes?

**Comment by nickvergessen** [comment]
Single user is not possible. Apart from that I don't know if getting the network traffic via php works at all.

**Comment by brantje** [comment]
Maybe we can use [phpSysinfo](http://phpsysinfo.github.io/phpsysinfo/demos.html) as api for this project?
It provides a lot of information, and works on a lot of systems.

**Comment by colttt** [comment]
why we need this? we want infos/healthstate about the software, in this case nextcloud, so why we care about the network traffic? for that you can use a monitoringprogramm.
That is not a task for nextcloud IMHO
