### ISSUE TITLE
Don't use shell_exec

### ISSUE THREAD

**Issue by oparoz** [nextcloud/serverinfo#50]
The `shell_exec` method is often blacklisted as it represents a security risk, so we should avoid using it.

Per example, when monitoring the memory, we should do it in PHP. Read `/proc/meminfo` and parse what we get.

Also, it should be mentioned somewhere that this only works on Linux as that path doesn't exist BSD systems.

**Comment by MorrisJobke** [comment]
Fixed with #57

**Comment by willemb2** [comment]
I'm new in the Nextcloud world so I don't know what happened between 2016 and 2022, but in NC 24.05 I get a flood of
`Error: shell_exec() has been disabled for security reasons at /home/<user>/domains/(our domain>/public_html/cloud/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#116`
when accessing Administration > System.

Your average shared webhosting does not allow shell_exec. 

With PHP 7.4 that Administration > System page still works, but with PHP 8.x it crashes:
`The server was unable to process your request (...)
    External address: 2a10:3781:15:1:a9f8:900a:ba7:dda9
    Request ID: YxxowmdQRzubW62uI-J4cwAAHxc`

And we get errors like:
`Call to undefined function OCA\ServerInfo\OperatingSystems\shell_exec() in file '/home/<account./domains/<our domain>/public_html/cloud/apps/serverinfo/lib/OperatingSystems/DefaultOs.php' line 227`
