### ISSUE TITLE
serverinfo not working with dashed db name

### ISSUE THREAD

**Issue by emiglio** [nextcloud/serverinfo#54]
Hi,
i updated from Nextcloud 10.0.0 to Nextcloud 10.0.1 today. 
The Serverinfo Tab didn't work after that.

In the Error Log i found: 
"Exception: {"Exception":"Doctrine\DBAL\Exception\SyntaxErrorException","Message":"An exception occurred while executing 'SHOW TABLE STATUS FROM database-suffx':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-suffix' at line 1..."

"database-suffix" is my database name

So i changed:

<pre>
 "$sql = 'SHOW TABLE STATUS FROM ' . $db_name;" 
to 
"$sql = 'SHOW TABLE STATUS FROM `' . $db_name . '`';"
</pre>

in the DatabaseStatistics.php in line 96

and it started working again.

I guess there may be some others with a "-" in their database name.

**Comment by ckujau** [comment]
FWIW, the file name from the snippet above is [lib/DatabaseStatistics.php:96](https://github.com/nextcloud/serverinfo/blob/4d38425c949b5ac4e49b76b8ea1ff3d94735b56b/lib/DatabaseStatistics.php#L96) and this is maybe related to commit 3ceadd822679dd1d6f288fd81a4ab0397b3c534b but I haven't bisected this issue to tell for sure.

**Comment by JarbyDev** [comment]
the @emiglio Solution works for me.

**Comment by tx7** [comment]
Hi,

I'm currently on NC 11, and I followed the solution above, and now I got a different error.

`syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) at /media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/apps/serverinfo/lib/DatabaseStatistics.php#100`

**Comment by MorrisJobke** [comment]
cc @schiessle @nickvergessen

**Comment by nickvergessen** [comment]
@tx7 then you made a little error while copying the code.
But you can also just replace the complete file with:
https://raw.githubusercontent.com/nextcloud/serverinfo/cd9720eb4bc89bf6d7d6c1d0e35a2f983669fe82/lib/DatabaseStatistics.php
