### ISSUE TITLE
No apps-related metrics in NC 28.0.2 (serverinfo 1.18.0)

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/serverinfo#561]
I have noticed that with Nextcloud 28.0.2 (serverinfo 1.18.0), the apps-related metrics (num_installed, num_updates_available,app_updates) are not in the output anymore, at least in the JSON format.

These metrics are present in Nextcloud 27.1.5.

I didn't try with intermediary releases.

Is there any particular reason?

**Comment by joshtrichards** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/release_notes/upgrade_to_28.html#monitoring

**Comment by pmarini-nc** [comment]
thanks
