### ISSUE TITLE
Cannot enable app on NC 9.0.52

### ISSUE THREAD

**Issue by totalcaos** [nextcloud/serverinfo#6]
Cannot enable the serverinfo application.

Attempted to modify info.xml

`<dependencies>
        <owncloud min-version="8.0" max-version="9.2" />
    </dependencies>`

**Error Message**

![image](https://cloud.githubusercontent.com/assets/20318996/17326493/0acd9d36-58f5-11e6-82b6-fb24fa9fb853.png)

NC Version 9.0.52
OS: Debian 8
PHP: 5.6

**Comment by totalcaos** [comment]
Took a while for cached information to update.  The app is enabled after modification described above

**Comment by nickvergessen** [comment]
Want to do a pull request @totalcaos

**Comment by totalcaos** [comment]
@nickvergessen I'll pull tonight and test

**Comment by schiessle** [comment]
pr was merged
