### ISSUE TITLE
Bug in Server Info App causes PHP errors in the log

### ISSUE THREAD

**Issue by timreeves** [nextcloud/serverinfo#61]
Hi,

I get lots of this in the NC log:

{"reqId":"tCN\/yPhSfCy+NCY46hLc","remoteAddr":"188.192.17.159","app":"PHP","message":"Undefined index: MemAvailable at /var/www/vhosts/{hid}/{hid}/apps/serverinfo/lib/SystemStatistics.php#85","level":3,"time":"2016-10-31T17:09:15+00:00","method":"GET","url":"/apps/serverinfo/update","user":"{hid}"}

I know there are some discussions about how free memory should be calculated, but here I'm talking about a BUG:

I'm running on a VPS at HostEurope, which uses the Virtuozzo Container Virtualisation paradigm. In this paradigm the "Wirtsystem" can allocate more or less memory to the individual virtual hosts, depending on circumstances. Be that as it may, "MemAvailable" and is NOT PRESENT in my output of /proc/meminfo, but "MemFree" is.

So you need to first check if that value is available and do something else if not.

apps/serverinfo/lib/SystemStatistics.php Line 85:
'mem_free' => (int)$data['MemAvailable'] + (int)$data['SwapFree'],

I have changed this to:
'mem_free' => (int)$data['MemFree'] + (int)$data['SwapFree'],

and now I can see the Server Info and no errors are generated.

Hope this fix finds its way into the official codebase soon! And thx to all!

**Comment by karlitschek** [comment]
@schiessle @Ivansss

**Comment by timreeves** [comment]
Thanks Frank!
BTW that's on Ubunto 14.04 LTS

**Comment by Ivansss** [comment]
Already fixed here #51.
It will be released with Nextcloud 10.0.2.
