### ISSUE TITLE
Show installed apps

### ISSUE THREAD

**Issue by nperez60** [nextcloud/serverinfo#610]
## Enhancement request

It would be great to display a list of the names of the installed apps in the serverinfo/api.  
I see that the list is already used to only display apps thats have an available update.

```php
	// load all apps
		$apps = $this->appManager->getInstalledApps();
		$info['num_installed'] = \count($apps);
```
		
An exemple output will be like :

```json
"installed_app": [
            "activity",
            "bruteforcesettings",
            "comments",
            "notifications",
            "serverinfo",
            "onlyoffice",
            "circles",
            "federatedfilesharing"
            "..."
          ]
```

This way it would allow us to carry out an audit of the applications installed of any instance base on the serverinfo/api.

**Comment by joshtrichards** [comment]
You might find the existing app management API useful for this: https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/instruction_set_for_apps.html

I'm not sure why this chapter is in the user management section of the Admin Manual. I think it got added a million years ago alongside user management API. Probably should get moved to the Apps Management section...

**Comment by nperez60** [comment]
@joshtrichards This actually meets my needs, thank you very much!
Sorry I searched but I missed it :/

**Comment by joshtrichards** [comment]
No worries! Tracking doc re-organization in nextcloud/documentation#11874
