### ISSUE TITLE
Wrong Max Execution Time in Serverinfo Page

### ISSUE THREAD

**Issue by thrdroom** [nextcloud/serverinfo#62]
### Steps to reproduce
1. Manual Update from 10.0.0 to 10.0.1
2. Check Max Execution Time in Serverinfo Page at http://CLOUD/index.php/settings/admin/serverinfo > Max Execution Time is: 3600
3. $ nano /etc/php/7.0/apache2/php.ini
4. change the value of max_execution_time to 1888
5. $ service apache2 restart
6. Check Max Execution Time in Serverinfo Page at http://CLOUD/index.php/settings/admin/serverinfo > Max Execution Time is: 3600
7. phpinfo(); shows correct Max Execution Time 1888

### Expected behaviour
Serverinfo Page should list the correct Max Execution Time as set in php.ini

### Actual behaviour
Serverinfo Page shows 3600 as Max Execution Time

### Server configuration
**Operating system**: Debian 8.6
**Web server:** Apache 2
**Database:** Mysql 5.7.16
**PHP version:** PHP 7.0.12
**Nextcloud version:** (see Nextcloud admin page) 10.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Nextcloud 10.0.0
**Where did you install Nextcloud from:** nextcloud-10.0.1.tar.bz2

**Comment by Ivansss** [comment]
Max execution time is set here:
https://github.com/nextcloud/server/blob/master/lib/base.php#L633
So even if you change it in apache php.ini, this value will be overwritten in the code above.

**Comment by nickvergessen** [comment]
Yeah, since that is what is being used and what counts, it is actually the correct value that should be displayed.

**Comment by mrclschstr** [comment]
Sorry, this might be a little bit offtopic, but how is it possible for the [base.php](https://github.com/nextcloud/server/blob/master/lib/base.php#L647) to override the `max_execution_time` defined in the `php.ini`?

In contrast to this, the `upload_max_filesize` defined in [base.php](https://github.com/nextcloud/server/blob/master/lib/base.php#L651) is overridden by the value defined in the `.htaccess` or `.user.ini` (at least with my setup). Is there any order in processing these settings?

**Comment by nickvergessen** [comment]
Ask php, but I think its: php.ini, .htaccess and then the script running itself, but it is optional to allow overwriting via htaccess and in a script.
