### ISSUE TITLE
activeUsers tag should be written in lowercase

### ISSUE THREAD

**Issue by j-ed** [nextcloud/serverinfo#626]
If you use the interface to query status information, all xml tags are written in lowercase, except the **'activeUsers'** tag, which is written in mixed writing. This should be aligned and also written in lowercase.
```
   </database>
  </server>
  <activeUsers>
   <last5minutes>1</last5minutes>
   <last1hour>4</last1hour>
   <last24hours>4</last24hours>
  </activeUsers>
 </data>
</ocs>'
```

### Steps to reproduce
1. request server information
2. check the xml syntax

### Expected behaviour
All tags should be written in lowercase.

### Actual behaviour
the **'activeUsers'** tag is written in mixed upper and lowercase writing.

### Server configuration
Nextcloud version: 28.0.6.1

**Comment by kesselb** [comment]
Is there a reason, apart from using the came casing for all items, to align it? 

Otherwise, I would keep it like that to avoid adjusting all API consumers.

**Comment by j-ed** [comment]
No, I just identified the issue as I tried to check user data and it didn't work in a first attempt. After further analysis I identified this issue and decided to report it.

**Comment by kesselb** [comment]
Okay
