### ISSUE TITLE
Error showing widget monitoring Nexcloud on gethomepage.dev

### ISSUE THREAD

**Issue by parveenrhce** [nextcloud/serverinfo#675]
I'm trying to integrate the monitoring from Nextcloud ServerInfo to my locally hosted gethomepage.dev. Both containers are running on Docker. But it's not working :(

I tried setup monitoring of my adblocker nad it's working fine so there is no issue with the locally hosted gethomepage.dev

-->
### Steps to reproduce

1.
#vi /opt/stacks/volumes/homepage/services.yaml
    - Nextcloud-PROD-Monitor:
        icon: nextcloud-timemanager.png
        widget:
          type: nextcloud
          url: http://10.10.20.10:5003/ocs/v2.php/apps/serverinfo/api/v1/info
          NC-Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXX   (hidden)
:wq!

2.
#vi /opt/stacks/volumes/homepage/services.yaml
    - Nextcloud-PROD-Monitor:
        icon: nextcloud-timemanager.png
        widget:
          type: nextcloud
          url: http://192.168.20.53:5003/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
          NC-Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXX   (hidden)
:wq!

3.
#vi /opt/stacks/volumes/homepage/services.yaml
    - Nextcloud-PROD-Monitor:
        icon: nextcloud-timemanager.png
        widget:
          type: nextcloud
          url: http://192.168.20.53:5003/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
          key: XXXXXXXXXXXXXXXXXXXXXXXXXXXX   (hidden)
:wq!

4.
#vi /opt/stacks/volumes/homepage/services.yaml
    - Nextcloud-PROD-Monitor:
        icon: nextcloud-timemanager.png
        widget:
          type: nextcloud
          url: http://10.10.20.10:5003/ocs/v2.php/apps/serverinfo/api/v1/info
          key: XXXXXXXXXXXXXXXXXXXXXXXXXXXX   (hidden)
:wq!

-----------------

5.
#vi /opt/stacks/volumes/homepage/services.yaml
    - Nextcloud-PROD-Monitor:
        icon: nextcloud-timemanager.png
        widget:
          type: nextcloud
          url: http://10.10.20.10:5003/ocs/v2.php/apps/serverinfo/api/v1/info
          NC-Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXX   (hidden)
          fields:
            - cpuload
            - memoryusage
            - freespace
            - activeusers
            - numfiles
            - numshares
:wq!

6.
#vi /opt/stacks/volumes/homepage/services.yaml
    - Nextcloud-PROD-Monitor:
        icon: nextcloud-timemanager.png
        widget:
          type: nextcloud
          url: http://192.168.20.53:5003/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
          NC-Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXX   (hidden)
          fields:
            - cpuload
            - memoryusage
            - freespace
            - activeusers
            - numfiles
            - numshares
:wq!

7.
#vi /opt/stacks/volumes/homepage/services.yaml
    - Nextcloud-PROD-Monitor:
        icon: nextcloud-timemanager.png
        widget:
          type: nextcloud
          url: http://192.168.20.53:5003/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
          key: XXXXXXXXXXXXXXXXXXXXXXXXXXXX   (hidden)
          fields:
            - cpuload
            - memoryusage
            - freespace
            - activeusers
            - numfiles
            - numshares
:wq!

8.
#vi /opt/stacks/volumes/homepage/services.yaml
    - Nextcloud-PROD-Monitor:
        icon: nextcloud-timemanager.png
        widget:
          type: nextcloud
          url: http://10.10.20.10:5003/ocs/v2.php/apps/serverinfo/api/v1/info
          key: XXXXXXXXXXXXXXXXXXXXXXXXXXXX   (hidden)
          fields:
            - cpuload
            - memoryusage
            - freespace
            - activeusers
            - numfiles
            - numshares
:wq!

### Expected behaviour
Should show the monitoring metrics like: "cpuload", "memoryusage", "freespace", "activeusers", "numfiles", "numshares", etc....

![image](https://github.com/user-attachments/assets/31cdeb25-7da2-4ade-8355-89be13375402)

### Actual behaviour
The Nextcloud monitoring metrics are not being displayed (see below screenshot)

![image](https://github.com/user-attachments/assets/c713b3f7-5e73-44d8-b0fc-f631c9030002)

### Server configuration

**Operating system**: "Debian GNU/Linux 12 (bookworm)" - Nextcloud Docker container

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** PHP 8.2.23

**Nextcloud version:** Nextcloud Hub 8 (29.0.6)

**Where did you install Nextcloud from:** Docker -> nextcloud:latest

**Comment by parveenrhce** [comment]
It shows API error:

![image](https://github.com/user-attachments/assets/dce4c7ff-80a6-4404-b888-f693d13d1e95)

**Comment by parveenrhce** [comment]
Output from the Nextcloud Docker container below:

_------------
root@XXXXXXXXXX:/var/www/html/apps/serverinfo# ls -ltr
total 124
-rw-r--r-- 1 www-data www-data 78151 Sep  4 20:25 composer.lock
-rw-r--r-- 1 www-data www-data   930 Sep  4 20:25 composer.json
-rw-r--r-- 1 www-data www-data 34519 Sep  4 20:25 COPYING
-rw-r--r-- 1 www-data www-data     0 Sep  4 20:25 CHANGELOG.md
-rw-r--r-- 1 www-data www-data    98 Sep  4 20:25 AUTHORS.md
drwxr-xr-x 1 www-data www-data    38 Sep  4 20:25 img
drwxr-xr-x 1 www-data www-data    18 Sep  4 20:25 css
drwxr-xr-x 1 www-data www-data    64 Sep  4 20:25 appinfo
drwxr-xr-x 1 www-data www-data    64 Sep  4 20:25 js
drwxr-xr-x 1 www-data www-data  2700 Sep  4 20:25 l10n
drwxr-xr-x 1 www-data www-data   400 Sep  4 20:25 lib
drwxr-xr-x 1 www-data www-data    36 Sep  4 20:25 templates
root@495e35d2869f:/var/www/html/apps/serverinfo#
------------------------------------_

**Comment by kesselb** [comment]
Hi,

I never used 


https://gethomepage.dev/main/widgets/services/nextcloud/

**Comment by kesselb** [comment]
Thanks for your report :+1: 

I don't know gethomepage.dev. 

According to their documentation[^1] and the implementation[^2] I assume you need to use `url: 192.168.20.53:5003`.

[^1]: https://gethomepage.dev/main/widgets/services/nextcloud/
[^2]: https://github.com/gethomepage/homepage/blob/main/src/widgets/nextcloud/widget.js
