### ISSUE TITLE
Handle non-accessible/non-existent /proc more gracefully

### ISSUE THREAD

**Issue by mbiebl** [nextcloud/serverinfo#68]
Version: 11.0.0

My hosting provider is all-inkl.com. In that hosting environment I do not have access to /proc and therefore /proc/meminfo.

When accessing the "Server Info" page as admin, "CPU Load" shows
Load average: undefined (Last minute)
"Memory usage" shows
Memory info not available

In the log file I get flodded with dozens of messages like this
```
file_get_contents(/proc/meminfo): failed to open stream: Permission denied at /www/htdocs/xxxxx/nextcloud/apps/serverinfo/lib/SystemStatistics.php#71
```
It would be nice if nextcloud would handle a non-accessible /proc more gracefully, and not floods the log file.
Also, the "Load average: undefined" message should be improved in such a case

**Comment by nickvergessen** [comment]
@schiessle

**Comment by cebolina** [comment]
I have exactly the same Problems with Version 11.0.0 on all-inkl.com.

**Comment by nickvergessen** [comment]
Can you try https://github.com/nextcloud/serverinfo/pull/71/files whether that stops the error from being written in the log?
The Info is still not available, but that is impossible

**Comment by mbiebl** [comment]
I think it should log one error message and then stop polling /proc/meminfo. Not simply hiding the error

**Comment by nickvergessen** [comment]
Well it's not an error exactly, and the UI shows that it is "not available"

Also the problem is, we don't know which one is the "first" polling. So it's an all or nothing and I think nothing is better then spaming.

**Comment by mbiebl** [comment]
I don't understand, how is
```
file_get_contents(/proc/meminfo): failed to open stream: Permission denied at /www/htdocs/xxxxx/nextcloud/apps/serverinfo/lib/SystemStatistics.php#71
```
not an error?

**Comment by nickvergessen** [comment]
Well it's just a feature that's not available, it technically is an error yes, but we could also do a file_exists before and that would also silence the log.

I think this together with #52 is the way to go.

**Comment by cebolina** [comment]
The workaround [https://github.com/nextcloud/serverinfo/pull/71/files](https://github.com/nextcloud/serverinfo/pull/71/files) works fine for me. It stops the error from being written in the log.

**Comment by fireheadman** [comment]
worked for me also...  Using nextcloud in a FreeNas jail.   Appreciate the fix!
