### ISSUE TITLE
Detail drilldown of links and shares

### ISSUE THREAD

**Issue by brianbgness** [nextcloud/serverinfo#69]
Requesting a count of shares amongst users, and click to drilldown to details of the active links and shares.

There is no expectation of user privacy in my organization.  Management wants to see what the users are sharing.  I realize the complexity of the request.  We're new to Nextcloud and your development model.  Please advise if you think it appropriate for me to query the database and roll out my own reports.  I think all Nextcloud admins would appreciate if such reporting was built into the product.

Kind regards,
Brian

**Comment by nickvergessen** [comment]
Sorry, but that is not something we can build into the official product.
