### ISSUE TITLE
Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000]

### ISSUE THREAD

**Issue by meyerdominik** [nextcloud/serverinfo#75]
### Steps to reproduce
1. Open adminpannel
2. Open serverinfo

### Expected behaviour
I should see the all serverinfo

### Actual behaviour
[Screenshot](http://prntscr.com/dpox61) 
[Apache errorlog](http://pastebin.com/6dc5Mz7U)

### Server configuration
**Operating system**: raspbian(debain) ver. 4.4.38-v7+ 

**Web server:** Apache/2.4.10 

**Database:** mysql 5.5.53-0+deb8u1

**PHP version:** 5.6.29-0+deb8u1

**Nextcloud version:** 10.0.2 

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**List of activated apps:**
<details>
<summary>Collaborative tags, Deleted files, External storage support, Federation, File sharing, Files automated tagging, Gallery, Notifications, Password policy, PDF viewer, Provisioning API, Server info, Text editor, Theming, Update notification, Versions, Video player, Contacts, Documents, Audio Player</summary>
</details>

**Comment by MorrisJobke** [comment]
> Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock

Check that your DB is up and running.
