### ISSUE TITLE
Add information about outstanding app updates

### ISSUE THREAD

**Issue by janvonde** [nextcloud/serverinfo#86]
To monitor the availability of app updates it would be nice to have this information in the api/v1/info endpoint.

**Comment by patschi** [comment]
I think that's a good idea to monitor outstanding app updates from different monitoring solutions. I have done that right now, using that kind of format:
![image](https://user-images.githubusercontent.com/2029878/27011108-246b43cc-4eb5-11e7-9fa1-03e9c3c5e795.png)

It provides easy numeric overview, additionally you are able to parse all available apps which has updates available, including the new version number. I've tried multiple ways, but I think this one tells the most required information while keeping the output as few and clean as possible.

How's the data format from the monitoring perspective @janvonde? If it's okay for @schiessle or @nickvergessen a PR would be ready.

**Comment by nickvergessen** [comment]
Looks good to me
I don't think there is an official standard for something like this, so go ahead

**Comment by patschi** [comment]
Okay, fine! PR created.
